### ISSUE TITLE
Bootloader stuck

### ISSUE THREAD

**Issue by teamyudin** [LedgerHQ/ledger-manager-chrome#19]
Upgrading to 4.1. 

The screen just shows "Bootloader". Tried to restart the extension, etc.

What should I try?

**Comment by etch1** [comment]
Same problem here, but it's stuck on "update" unless you plug it in while holding the left button (with ledger manager open) and release. Ledger manager doesn't diplay anything other than "To begin, connect your ledger wallet."

Installed the chrome-app.zip version, no difference.

https://support.ledgerwallet.com/hc/en-us/articles/360000608113

So, on this guide, I am stuck on "go to firmware" since the app is unresponsive.

**Comment by mssteuer** [comment]
Same issue. Stuck on "update"... can't get out of the loop

**Comment by sirstu** [comment]
Same Issue it's stuck on bootloader, Won't update just says restoring MCU which I left for over an hour before unplugging & trying again. I thought maybe unplug & reset to factory settings & update before recoveryphase step etc but whenever I plug it in now it goes straight to bootloader & it's just not updating. reinstalled ledger manager, tried different USB ports & leads but nothing. Seems to be stuck in update mode without actually updating.?

**Comment by amougel** [comment]
For stuck on "update", you can try installing this version:

Download https://github.com/LedgerHQ/ledger-manager-chrome/releases/download/1.0.1/chrome-app.zip

Unzip it

Go to chrome://extensions/, activate developer mode and "load unpacked extension" and select the folder you extracted

Launch it

In the firmware section; click on install

**Comment by sirstu** [comment]
The ledger still goes straight to bootloader but the ledger manager app
just stays on the screen that says "to begin, connect your ledger wallet as
though it not recognised that the wallet is plugged in...

**Comment by sirstu** [comment]
I don't even need to press the left button on the ledger for it to go to
bootloader, it just does it as soon as I plug the ledger in...

**Comment by joezys** [comment]
What the hell is wrong with Ledger to leave this unaddressed for two months?  I have the exact same problem as a result of trying to update to the 1.5.1 firmware.  I followed the instructions exactly then got the error message the the MCU was outdated.  Followed the instructions and got stuck on Bootloader.  Plugged the Nano S back in while holding down the first button ... got stuck on Update!  Downloaded the chrome extension from https://github.com/LedgerHQ/ledger-manager-chrome/releases/tag/1.0.1 following all of their instructions and still stuck on Update!  There is obviously a problem that many people are having.  I can't access my crypto because the update process is defective and my Nano S is now useless.  Is it overly demanding to expect someone at Ledger would take this seriously and come up with a fix that works?  FRUSTRATED BEYOND BELIEF!!!!!!!!!!!!!!!!!

**Comment by shmond** [comment]
Has anyone addressed this yet? I'm with etch1, did everything asked but I am still stuck with UPDATE on the Nano S and TO BEGIN, CONNECT YOUR LEDGER WALLET on the manager. Can't access firmwares

**Comment by shmond** [comment]
So per the below link, it looks like using Windows 7 may be the issue. Trying again tonight on a different computer.

https://support.ledgerwallet.com/hc/en-us/articles/360003117594?input_string=firmware+upgrade+failed%2C+stuck+on+bootloader%2Fupdate

**Comment by joezys** [comment]
I am unable to get the new firmware to work with Windows 7.

**Comment by vampyren** [comment]
I made the misstake to use update bootloader instead or recover and not its stuck!
How the hell can i cancel the bootloader update process??? its wont ever complete. The Chrome extention is stuck at "Restoring MCU" and ledger is stuck at "Bootloader" after hours. I re-installed extention, rebooted pc, replaced cable, tried another USB port, checked device manger for yellow ! signs (dont have them so drivers are fine) and even tried on my Mac. Nothing works. I'm on Windows 10 x64 and latest updates. 
This is ridiculous! How can i cancel or complete this bootloader update nonsense. Hasnt anyone tried to do the update on the same version? it should skip if its the same version or something. Not get stuck like this! Already filed a ticket with support as well. Hope they get back with a proper answer and not a silly "restart your pc" or something.

**Comment by sirstu** [comment]
Mate I've done all this & got it stuck on two ledgers that I recommended to
2 friends. I've done exactly the same as u & even bought a new laptop coz
thought it could be the fact I was using windows 7, which ledger support
told me it would be... Still no answer so I have 2 unusable ledgers, I'm
not going to recommend ledger again. It's a shame coz when they work they
are great but this problem needs to be sorted...

**Comment by btchip** [comment]
Please contact support, as each issue is OS / configuration specific

**Comment by vampyren** [comment]
I have to give Ledger credit for handling one of the issues. I have filed 2 tickets. One for Ledger Blue and one with this problem for Ledger Nano S. 
For the latter they already acknowledged that they will send me a new Ledger Nano S. Hope you can get the same @sirstu . My issue was also with the screen so maybe that helped speed up things. Hope they replace yours too mate. Its so annoying when it gets stuck and there is nothing you can do. It should atleast be possible to set the device into a factory setting in any situation.

**Comment by sirstu** [comment]
I've got in contact again today & they are gonna take them both back, I've
asked for replacements rather than refund just waiting to hear back now...
They have been good at replying to emails it's just bit of a ball ache coz
they where bought by 2 indavidual people who invest through me & I
recommended these as the best option to store their coins.. so need to find
out if I can send back on their behalf or if they need to do it themselves.
Not heard back from ledger yet but sure it'll get sorted in the end. Just
really glad I didn't send their holdings to either ledger before this
happened. But it does seem that this is a common problem that needs to be
addressed...

**Comment by vampyren** [comment]
Yes the issue is common if you google this. Good thing is the 24 word will recover everything so its good to know your funds are safe.

**Comment by gorebang** [comment]
I've got this issue now as well.  Absolute garbage.

I'm wondering if I can use the 24 word recovery mechanism on a trezor or something different.  I don't really want to sink any more money on such a faulty product.

**Comment by vampyren** [comment]
Yes you can with some reservation. Like Trezor does not support all the tokens and for ETH i got strange issues. 
I would still get a new Ledger (maybe the new model). They are now cheap (S model) and work pretty well beside that. We are early adopters so this is the downside. 
Also if you contact Ledger you might get a new one without cost. Did you try that?

**Comment by amougel** [comment]
@gorebang Have you tried [this ](https://support.ledger.com/hc/en-us/articles/360003117594-Troubleshoot-firmware-update)?

**Comment by joezys** [comment]
If you update to the new firmware it is NOT compatible with Windows 7.  You
will need to use a Windows 10 machine instead.  There is no way to go back
to the old firmware that I'm aware of once you "upgrade."

**Comment by vampyren** [comment]
> 
> 
> @gorebang Have you tried [this ](https://support.ledger.com/hc/en-us/articles/360003117594-Troubleshoot-firmware-update)?

Damn this actually helped! i was stuck at Bootloaded and it unstuck the ledger! Thanks for the tips. Sadly my ledger is/was pretty broken even from before. The LCD is finicky with a row full of dead pixels. Ledger send me a new one so it sorted itself out but still its good to know about this fix.

**Comment by abdulbrb** [comment]
I have rebooted my computer (Windows 7) in Safe mode with networking , and I updated my ledger successfully.

**Comment by joezys** [comment]
What do you mean, rebooted Windows 7 with networking?  Your updated Ledger
now works with Windows 7?

**Comment by abdulbrb** [comment]
Yes ledger (Firmware version 1.5.5) works fine in my windows 7, In order to update my ledger I have rebooted my computer in safe mode with networking. check [this] : https://support.ledger.com/hc/en-us/articles/360003117594-Troubleshoot-firmware-update

**Comment by Alexipsc** [comment]
Just be careful when rebooting windows 10 in safe mode. I did that especially for updating the Ledger and than I  wasn't able to login anymore into my PC as apparently in Safe mode switches from PIN to Microsoft account password but when trying to insert my password it won't recognize it as I didn't have access to internet anymore in Safe mode (Even on Safe mode with networking and Ethernet cable !! )

**Comment by agongdai** [comment]
I am on Ubuntu 19.04. This article saved me: https://support.ledger.com/hc/en-us/articles/115005165269.

`2. Troubleshooting` => `Option 1`

**Comment by eloudsa** [comment]
Thanks @agongdai !
I found my solution on the video linked with the article. I had an older Ledger chrome extension. I removed it and FINALLY I was able to go out from  the bootloader process and to install the new firmware.
